"""empty message

Revision ID: 231a85d8c738
Revises: 10161cb6c92a
Create Date: 2019-02-27 06:15:16.761201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231a85d8c738'
down_revision = '10161cb6c92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('todo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
